version = '2'

[run]
tests = true

[linters]
default = 'none'
enable = [
  'asciicheck',
  'bidichk',
  'bodyclose',
  'contextcheck',
  'copyloopvar',
  'decorder',
  'dogsled',
  'dupl',
  'dupword',
  'errcheck',
  'errname',
  'errorlint',
  'exhaustive',
  'forcetypeassert',
  'gocheckcompilerdirectives',
  'gocyclo',
  'godot',
  'gomoddirectives',
  'govet',
  'ineffassign',
  'intrange',
  'misspell',
  'nakedret',
  'nilerr',
  'nilnil',
  'nolintlint',
  'noctx',
  'prealloc',
  'predeclared',
  'reassign',
  'staticcheck',
  'tagalign',
  'usetesting',
  'testifylint',
  'unconvert',
  'unparam',
  'unused',
  'wastedassign',
  'whitespace',
  'wrapcheck',
]

[linters.settings.exhaustive]
default-signifies-exhaustive = true


[linters.settings.gocyclo]
min-complexity = 20

[linters.settings.staticcheck]
checks = [
  'all',
  '-ST1001',
  '-ST1003',
  '-ST1005',
]

[linters.settings.wrapcheck]
ignorePackageGlobs = [
  'github.com/kirill-jjj/nvdaRemoteServer/server',
]

[linters.settings.tagalign]
align = false
sort = true

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling',
]
paths = [
  'third_party$',
  'builtin$',
  'examples$',
]

[issues]
fix = true

[formatters]
enable = [
  'gofumpt',
]

[formatters.settings]
[formatters.settings.gofumpt]
extra.group-params = true

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$',
]
